# Generated by Django 3.1.5 on 2021-01-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='account1',
        ),
    ]
